import type { Metadata } from 'next'
import { Gluten } from 'next/font/google'
import localFont from 'next/font/local'

import './globals.css'
import Footer from '@/components/footer'
import Navbar from '@/components/navbar'
import { cn } from '@/lib/utils/shadcn'

// set Favorit as the global default font this also sets the font for shad cn components
// see https://ui.shadcn.com/docs/installation/next
// const favorit_sans = localFont({
//   src: [{ path: '../../public/fonts/favorit-regular.woff2', style: 'normal' }],
//   variable: '--font-sans',
// })
// const favorit_mono = localFont({
//   src: [{ path: '../../public/fonts/favorit-mono.woff2', style: 'normal' }],
//   variable: '--font-mono',
// })

const gluten = Gluten({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(gluten.variable, 'dark font-sans')}>
        <Navbar />
        <div className="min-h-content pt-navbar">{children}</div>
        <Footer />
      </body>
    </html>
  )
}
